config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/dashboard', to: 'pages#dashboard'
  resources :systems, only: %i[index show]
  # resources :reviews, only: %i[new create show edit update destroy] do
    # resources :comments, only: %i[new create edit update destroy]
  # end
  resources :games, only: %i[index show] do
    resources :reviews, only: %i[new create]
  end
  resources :reviews, only: %i[edit update destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

# systems: index of systems, no other crud actions (systems are basically static)
# games: index of games per system, also static (eventually API)
# reviews: index of reviews per game, crud actions (new, create, edit, update, destroy)
# comments: index of comments per game, crud actions (new, create, edit, update, destroy)

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/models/game.rb
class Game < ApplicationRecord
  include PgSearch::Model

  belongs_to :system
  has_many :reviews

  pg_search_scope :game_search,
                    against: {
                      name: 'A',
                      year: 'B',
                      developer: 'C'
                    },
                    associated_against: {
                      system: {
                        name: 'A',
                        company: 'B',
                        year: 'C'
                      }
                    },
                    using: { tsearch: { prefix: true} }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :game
  belongs_to :user

  validates :title, :content, :rating, presence: true
  validates :rating, inclusion: { in: [1, 2, 3, 4, 5] }
end

app/models/system.rb
class System < ApplicationRecord
  has_many :games
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    if params[:query].present?
      @games = Game.game_search(params[:query])
    else
      @games = Game.all
    end
  end

  def show
    @game = Game.find(params[:id])
    @reviews = Review.all
    @review = Review.new
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end

  def dashboard
    @user = current_user
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_game

  def new
    @review = Review.new
    @game = set_game
  end

  def create
    @review = Review.new(review_params)
    @review.user = current_user
    @review.game = set_game
    respond_to do |format|
      if @review.save
        format.html { redirect_to game_path(@review.game) }
        format.json
      else
        format.html { render "games/show" }
        format.json
      end
    end
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])
    @review.update(review_params)
    redirect_to game_path(@review.game)
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to game_path(@review.game)
  end

  private

  def set_game
    @game = Game.find(params[:game_id]) if params[:game_id]
  end

  def review_params
    params.require(:review).permit(:title, :content, :rating)
  end
end

app/controllers/systems_controller.rb
class SystemsController < ApplicationController
  before_action :find_system, only: [:show]

  def index
    @systems = System.all
  end

  def show
    @games = Game.where(system_id: @system.id)
  end

  private

  def find_system
    @system = System.find(params[:id])
  end

  def system_params
    params.require(:system).permit(:name, :year, :company)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/_review.html.erb
<div class="nes-container is-dark with-title">
  <p class="title"> <%= review.title %>
    <% review.rating.times do %>
      <i class="nes-icon is-small star"></i>
    <%end%>
  </p>
  <p> <%= review.content %> </p>
  <%= link_to "<button type='button' class='nes-btn is-warning'>Edit</button>".html_safe, edit_review_path(review) %>
  <%= link_to "<button type='button' class='nes-btn is-error'>Delete</button>".html_safe, review_path(review), method: :delete, data: { confirm: "Are you sure you want to delete this review?" } %>
</div>

app/views/games/index.html.erb
<div class="cards-wrapper">
  <div class="cards">
    <% @games.each do |game| %>
    <div class="card nes-container with-title is-centered">
      <p class="title"><%= game.name %></p>
      <p><%= game.year %></p>
      <p><%= game.developer %></p>
      <p><%= game.system.name %></p>
      <p><%= game.system.company %></p>
      <p><%= link_to "See details", game_path(game)%></p>
    </div>
    <% end %>
  </div>
</div>

app/views/games/show.html.erb
<div class="container">
  <h1> <%= @game.name %> </h1>
  <div data-controller="reviews">
    <div data-reviews-target="review">
      <% unless @game.reviews.nil?%>
        <% @game.reviews.each do |review| %>
          <%= render 'review', review: review %>
        <%end%>
      <% end %>
    </div>

    <div data-controller="newreview">
      <div class="nes-container with-title is-centered">
        <p class="title">Options</p>
        <button type="button" class="nes-btn is-primary" data-action="click->newreview#show">Review</button>
        <button type="button" class="nes-btn is-error d-none" data-action="click->newreview#hide" data-target="newreview.cancel reviews.cancel">Cancel</button>
        <div data-target="newreview.form reviews.new" class="d-none">
        <br>
          <div class="nes-container with-title is-centered">
            <p class="title">Leave a review</p>
            <%= render 'reviews/new' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BitSizedReviews</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="./node_modules/nes.css/css/nes.min.css">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <div class="page-container">
      <div>
        <%= render 'shared/navbar' %>
        <%= render 'shared/flashes' %>
      </div>
      <div>
        <%= yield %>
      </div>
      <div>
        <%= render 'shared/footer' %>
      </div>
    </div>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container">
  <div class="row mb-3">
    <div class="col-6">
      <div class="userinfo nes-container with-title is-centered">
        <p class="title">User information</p>
        <h5>Username: <%= @user.user_name %></h5>
        <h5>Email: <%= @user.email %></h5>
        <h5>Number of reviews: <%= @user.reviews.length %></h5>
        <h5>Average review rating: <%= @user.reviews.average(:rating) %></h5>
      </div>
    </div>
    <div class="col-6">
      <div class="userinfo nes-container with-title is-centered">
        <p class="title">Maybe some other stuff can go here</p>
        <h5>Some stuff</h5>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-6 reviewlist">
      <div class="userinfo nes-container with-title is-centered">
      <p class="title">User reviews</p>
      <% @user.reviews.each do |review| %>
        <div class="nes-container with-title mb-3">
          <p class="title"><%= link_to review.game.name, game_path(review.game) %></p>
          <div class="nes-container is-dark with-title mb-3">
            <p class="title"> <%= review.title %>
              <% review.rating.times do %>
                <i class="nes-icon is-small star"></i>
              <%end%>
            </p>
            <p> <%= review.content %> </p>
          </div>
        </div>
      <% end %>
      </div>
    </div>
    <div class="col-6">
    <div class="userinfo nes-container with-title is-centered">
      <p class="title">Other stuff, maybe user comments?</p>
    </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container">
  <div class="nes-container with-title is-centered">
    <p class="title">Take a look around!</p>
    <ul class="homepage-list">
      <li><%= link_to "Games", games_path %></li>
      <li><%= link_to "Systems", systems_path %></li>
    </ul>
    <div class="game-search-bar d-flex">
      <% if user_signed_in? %>
        <%= form_tag games_path, class: "d-flex mb-3", method: :get do %>
          <%= text_field_tag :query,
            params[:query],
            required: true,
            class: "nes-field",
            placeholder: " Find a game"
          %>
          <%= submit_tag "Search", class: "nes-btn is-primary" %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
<br>
<div class="container">
  <div class="nes-container with-title is-centered">
    <p class="title">About this site</p>
    <p>Made with <i class="nes-icon is-small heart"></i> by the nerds from batch 894. The code is open to anyone who wishes to contribute!</p>
    <p>The actual purpose of this site is to provide users with a place to rant about games they've played, be they new releases or old classics.</p>
    <p>Cool arbitrary progress bar:</p>
    <progress class="nes-progress is-warning" value="30" max="100"></progress>
  </div>
</div>

app/views/reviews/_edit.html.erb
<%= simple_form_for([@game, @review], data: { reviews_target: "form", action: "submit->reviews#send"}) do |f| %>
  <%= f.input :title, class: "nes-field" %>
  <%= f.input :content, class: "nes-textarea" %>
  <%= f.input :rating, class: "nes-select"%>
  <%= f.button :submit, class: "nes-btn is-primary" %>
<% end %>

app/views/reviews/_new.html.erb
<%= simple_form_for([@game, @review], data: { reviews_target: "form", action: "submit->reviews#send"}) do |f| %>
  <%= f.input :title, class: "nes-field" %>
  <%= f.input :content, class: "nes-textarea" %>
  <%= f.input :rating, collection: [["Awful",1], ["Meh", 2], ["Average", 3], ["Pretty funny", 4], ["Absolutely awesome", 5]], input_html: {data: {controller: "starrating"}}%>
  <%= f.button :submit, class: "nes-btn is-primary" %>
<% end %>

app/views/reviews/edit.html.erb
<%= simple_form_for(@review) do |f| %>
  <%= f.input :title, class: "nes-field" %>
  <%= f.input :content, class: "nes-textarea" %>
  <%= f.input :rating, class: "nes-select"%>
  <%= f.button :submit, class: "nes-btn is-primary" %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="clear"></div>
<div class="footer">
  <div class="footer-copyright">
    <p>#894</p>
    <a href="https://github.com/spethspeth/bit-sized-reviews" target="_blank"><i class="nes-octocat animate"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <h3><span id="bforbit">B</span>it<span id="sforsized">S</span>ized<span id="rforreviews">R</span>eviews<span id="greenperiod">.</span></h3>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Systems", systems_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://www.gravatar.com/avatar?s=15", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>
<div class="clear"></div>

app/views/systems/index.html.erb
<div class="cards-wrapper">
  <div class="cards">
    <% @systems.each do |system| %>
    <div class="card nes-container with-title is-centered">
      <p class="title"><%= system.name %></p>
      <p><%= system.company %></p>
      <p><%= system.year %></p>
      <p><%= link_to "See all #{system.name} games", system_path(system) %></p>
    </div>
    <% end %>
  </div>
</div>

app/views/systems/show.html.erb
<div class="container">
  <div class="nes-container with-title is-centered">
    <p class="title"><%= @system.name %></p>
    <p>Released:<%= @system.year %></p>
    <p>Company: <%= @system.company %></p>
  </div>
</div>
<br>
<div class="container">
  <div class="nes-container with-title is-centered">
    <p class="title">Games on <%= @system.name %></p>
    <ul class="homepage-list">
      <% @games.each do |game| %>
        <li><%= link_to game.name, game_path(game) %></li>
      <% end %>
    </ul>
  </div>
</div>
<br>
<div class="container">
  <div class="nes-container with-title is-centered">
    <p class="title">Options</p>
    <%= link_to "Back", systems_path %>
    <%#= link_to "Add a game", new_game_path %>
  </div>
</div>